language: python
python:
  - "2.7"

install:
  - pip install -e . --use-mirrors
  - pip install --use-mirrors coverage coveralls

services:
  - memcache

before_script:
  - mkdir -p ~/kegbot-data/media
  - mkdir -p ~/kegbot-data/static
  - mkdir -p ~/.kegbot/
  - cp deploy/travis/local_settings.py ~/.kegbot/

script:
  - kegbot test --traverse-namespace --first-package-wins --with-coverage --cover-package=pykeg

after_success:
  - coveralls